[Loss]
type = "L2" 

[Optimizer]
type = "Adam"
learning_rate = 1e-2
beta1 = 0.9
beta2 = 0.99
epsilon = 1e-15
l2_reg = 1e-6

[Hash]
n_levels = 16
n_features_per_level = 2
log2_hashmap_size = 19
base_resolution = 16

[SphericalHarmonics]
degree = 4

[DensityNetwork]
n_neurons = 64
n_hidden_layers = 1

[RgbNetwork]
n_neurons = 64
n_hidden_layers = 2